---
apiVersion: v1
kind: Service
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
  labels:
    app: wordpress
  name: wordpress-svc
  namespace: exercise-03
spec:
  ports:
    -
      port: 80
  selector:
    app: wordpress
  targetPort: 80
