apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: exercise-02
  labels:
    app: wordpress
    service: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wordpress
        service: frontend
        tier: stable
    spec:
      containers:
      - image: bitnami/wordpress:4.9.4
        name: wordpress
        env:
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wordpress.mariadb.host
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: database.name
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: database.user
        - name: WORDPRESS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wp.user
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-password
              key: password
        - name: WORDPRESS_BLOG_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wp.blog
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-mariadb-password
              key: password
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 25
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 25
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10