apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: exercise-01
  labels:
    app: mariadb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: bitnami/mariadb:latest
          name: mariadb
          ports:
          - containerPort: 3306
            name: dbport

          env:
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: wpuser

          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: wpdb

          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: wppass

          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: rootpw
   
          