apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-01
  labels:
    app: wordpress
    type: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
        type: frontend

    spec:
      containers:
      - image: bitnami/wordpress:latest        
        name: wordpress
        env:
          - name: MARIADB_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: hostname

          - name: MARIADB_PORT_NUMBER
            value: "3306"
              
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbname

          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbuser

           - name: WORDPRESS_USER
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: userwp

          - name: WORDPRESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: passwordwp

          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbpass     

          - name: WORDPRESS_BLOG_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: blogname         

          - name: WORDPRESS_TABLE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: prefixtable

        ports:
        - name: http
          containerPort: 80
