apiVersion: v1
data:
  MARIADB_HOST: "mariadb"
  MARIADB_PORT_NUMBER: "3306"
  WORDPRESS_DATABASE_NAME: "wordpress"
  WORDPRESS_DATABASE_USER: "wordpress"
  WORDPRESS_USERNAME: "admin"
  WORDPRESS_FIRST_NAME: "Daniel"
  WORDPRESS_LAST_NAME: "Dominguez"
  WORDPRESS_BLOG_NAME: "K8S TRAINING BLOG"
kind: ConfigMap
metadata:
  name: wordpress
