apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "lemp.fullname" . }}mariadb
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
spec:
  serviceName: {{ template "lemp.fullname" . }}mariadb
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "lemp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: "{{ .Chart.Name }}database"
        image: "{{ .Values.mariadb.repository }}:{{ .Values.mariadb.tag }}"
        imagePullPolicy: {{ .Values.mariadb.pullPolicy | quote }}
        env:
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "lemp.fullname" . }}
              key: dbUse
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "lemp.fullname" . }}
              key: dbPass
        - name: MARIADB_DATABASE
          valueFrom:
            secretketRef:
              name: {{ template "lemp.fullname" . }}
              key: dbName
        ports:
        - name: db-port
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            initialDelaySeconds: 90
            timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            initialDelaySeconds: 60
            timeoutSeconds: 3
        volumeMounts:
        - name: persistence
          mountPath: /bitnami/mariadb
      volumes:
        - name: persistence
          persistenVolumeClaim:
            claimName: {{ template "lemp.fullname" . }}
