apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  myapp.conf: |-
{{- if .Values.nginx.vhost }}
{{ .Values.nginx.vhost | indent 4 }}
{{- end -}}
