apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lemp.fullname" . }}
  namespace: {{.Values.namespace}}
type: Opaque
data:
  dbuser: {{ .Values.db.dbuser| b64enc }}
  dbpassword: {{ .Values.db.dbpassword| b64enc }}
