apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.host }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ .Chart.Name }}-svc
          servicePort: 80




