
host: session02-exercise-01.com

nginx:
  image: bitnami/nginx:latest
  pullPolicy: IfNotPresent
  replicaCount: 1

phpfpm:
  image: bitnami/php-fpm:latest
  pullPolicy: IfNotPresent

mariadb:
  image: bitnami/mariadb:latest
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  rootpassword: "root"
  forcePassword: false
  user: "test"
  password: "test"
  databasename:	"test" 
  serviceType: ClusterIP 
  servicePort: 3306
  strategyTpe: RollingUpdate
  
gitImage:
  registry: docker.io
  repository: alpine/git
  tag: latest
  pullPolicy: IfNotPresent
  
## Git repository http/https
##
repository: https://github.com/bitnami-labs/k8s-training-resources

## Git repository revision to checkout
##
revision: master

nginxService:
  name: nginx
  type: NodePort
  port: 80
phpfpmService:
  name: phpfpm
  type: NodePort
  port: 9000

pathapp: /app
