apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
  namespace: exercise-01

data:
  allow_empty_password: "no"
  mariadb_host: mariadb
  mariadb_port_number: "3306"
  wordpress_database_name: bitnami_wordpress

