apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: exercise-01
  labels:
    app: {{ .Release.Name }}
data:
  nginx-config.conf: |-
{{ .Values.frontend.nginx.config | indent 4 }}
  MARIADB_DATABASE: mariadb
