apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lemp.fullname" . }}
  namespace: exercise-01
data:
  MARIADB_ROOT_USER: {{ default "root" .Values.backend.mariadb.settings.root_user | b64enc }}
  MARIADB_USER: {{ required "Please specify a MariaDB user" .Values.backend.mariadb.settings.db_user | b64enc }}
  MARIADB_ROOT_PASSWORD: {{ required "Please specify a MariaDB root password" .Values.backend.mariadb.settings.root_password | b64enc }}
  MARIADB_PASSWORD: {{ required "Please specify a MariaDB user password" .Values.backend.mariadb.settings.db_password| b64enc }}
