---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-vision-resquota
  namespace: team-vision
spec:
  hard: # Quotas go here
    requests.cpu: 1.6 # 80% of 2 CPU = 2 * 0.8
    requests.memory: 3200Mi # 80% of 4Gb
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-api-resquota
  namespace: team-api
spec:
  hard: # Quotas go here
    requests.cpu: 400m # 20% of 2 CPU = 2 * 0.2
    requests.memory: 800Mi # 20% of 4Gb