kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: team-vision-readonly
  namespace: team-vision
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name:   team-vision-admin
  namespace: team-vision
rules:
  - apiGroups: [""]
    resources: # Everything except secrets
    - componentstatuses
    - configmaps
    - daemonsets
    - deployments
    - events
    - endpoints
    - horizontalpodautoscalers
    - ingress
    - jobs
    - limitranges
    - namespaces
    - nodes
    - pods
    - persistentvolumes
    - persistentvolumeclaims
    - resourcequotas
    - replicasets
    - replicationcontrollers
    - serviceaccounts
    - services
    verbs: ["create", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name:   team-vision-superadmin
  namespace: team-vision
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-team-vision-read-only
  namespace: team-vision
subjects:
- kind: Group
  name: dev # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: team-vision-readonly
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tech-lead-team-vision-admin
  namespace: team-vision
subjects:
- kind: Group
  name: tech-lead # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: team-vision-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vision-team-vision-admin
  namespace: team-vision
subjects:
- kind: Group
  name: vision # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: team-vision-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sre-team-vision-superadmin
  namespace: team-vision
subjects:
- kind: Group
  name: sre # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: team-vision-superadmin
  apiGroup: rbac.authorization.k8s.io