apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "lemp.name" . }}
      chart: {{ template "lemp.chart" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "lemp.name" . }}
        chart: {{ template "lemp.chart" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: gitclone
        image: "{{ .Values.image.git.registry }}/{{ .Values.image.git.repository }}:{{ .Values.image.git.tag }}"
        command: ["sh", "-c", "git clone https://github.com/bitnami-labs/k8s-training-resources/ /app; cd /app; git pull;"]
        volumeMounts:
        - name: nginx-data
          mountPath: /app
      containers:
      - name: nginx
        image: "{{ .Values.image.nginx.registry }}/{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
        imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: nginx-data
          mountPath: /app
        - name: nginx-vhost
          mountPath: /bitnami/nginx/conf/vhosts
        resources:
{{ toYaml .Values.resources | indent 10 }}
      - name: php-fpm
        image: "{{ .Values.image.php.registry }}/{{ .Values.image.php.repository }}:{{ .Values.image.php.tag }}"
        imagePullPolicy: {{ .Values.image.php.pullPolicy }}
        volumeMounts:
        - name: nginx-data
          mountPath: /app
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: {{ template "lemp.fullname" . }}
      - name: nginx-vhost
        configMap:
          name: {{ template "lemp.fullname" . }}

