apiVersion: v1
data:
  MARIADB_ROOT_PASSWORD: {{ required "MariaDB Root Password required!" .Values.mariadb.rootPassword | b64enc }}
  MARIADB_PASSWORD: {{ required "MariaDB Database Password required!" .Values.mariadb.dbPassword | b64enc }}
kind: Secret
metadata:
  name: {{ template "mariadb.fullname" . }}
