apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-02
  labels:
    app: wordpress
    type: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
        type: frontend
        label: stable

    spec:
      containers:
      - image: bitnami/wordpress:4.9.4
        name: wordpress
        env:
          - name: MARIADB_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: hostname

          - name: MARIADB_PORT_NUMBER
            value: "3306"
              
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbname

          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbuser

          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbpass     

          - name: WORDPRESS_BLOG_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: blogname         

          - name: WORDPRESS_TABLE_PREFIX
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: prefixtable

        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
       