---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-svc
  namespace: exercise-02
spec:
  ports:
    -
      port: 3306
  selector:
    app: mariadb
  targetPort: 3306
  type: ClusterIP
