apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.app.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "sampleapp.fullname" . }}
          servicePort: {{ .Values.sampleapp.service.port }}