apiVersion: v1
kind: Service
metadata:
  name: {{ template "sampleapp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: frontend
spec:
  type: {{ .Values.sampleapp.service.type }}
  ports:
    - name: http
      port: {{ .Values.sampleapp.service.port }}
      targetPort: {{ .Values.sampleapp.nginxport }}
  selector:
    app: {{ template "lemp.name" . }}
    release: {{ .Release.Name }}
    tier: frontend