{{- if .Values.persistence.enabled -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- end }}