---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-svc
  namespace: exercise-01
spec:
  ports:
    -
      port: 3306
  selector:
    app: mariadb
  type: ClusterIP
