apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mariadb
    service: database
  name: mariadb-deployment
  namespace: exercise-01
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mariadb
        service: database
    spec:
      containers:
        -
          env:
            -
              configMapKeyRef:
                key: mariadb_host
                name: wordpress-mariadb-config-map
              name: MARIADB_HOST
              valueFrom: ~
            -
              name: MARIADB_ROOT_USER
              secretKeyRef:
                key: mariadb_root_user
                name: wordpress-secrets
              valueFrom: ~
            -
              name: MARIADB_ROOT_PASSWORD
              secretKeyRef:
                key: mariadb_root_password
                name: wordpress-secrets
              valueFrom: ~
          image: "bitnami/mariadb:latest"
          name: mariadb
          ports:
            -
              containerPort: 3306
              name: mariadb
