apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: exercise-03
type: Opaque
data:
  database: azhzX3RyYWluaW5nX2RiXzE0
  username: azhzX3RyYWluaW5nX3VzZXJfMTQ=
  password: Yml0bmFtaS10cmFpbmluZy0yMDE4
