---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-03
  labels:
    app: wordpress
    track: stable
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress:4.9.4
          env:
            - name: WORDPRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-credentials
                  key: username
            - name: WORDPRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-credentials
                  key: password
            - name: WORDPRESS_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: WORDPRESS_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database
            - name: MARIADB_HOST
              value: external-database
            - name: WORDPRESS_FIRST_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-credentials
                  key: firstname
            - name: WORDPRESS_LAST_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-credentials
                  key: lastname
            - name: WORDPRESS_BLOG_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-credentials
                  key: blogname
          livenessProbe:
            httpGet:
              path: /wp-admin
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /wp-admin
              port: http
            initialDelaySeconds: 30
          ports:
            - containerPort: 80
              name: http
