apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.nginxService.type }}
  ports:
  - name: http
    port: {{ .Values.nginxService.port }}
    targetPort: http
  selector:
    app: {{ .Chart.Name }}
