apiVersion: v1
kind: Secret
metadata:
  name: db-{{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  user: {{- b64enc .Values.dbdata.user }}
  password: {{- b64enc .Values.dbdata.password }}
  root_password: {{- b64enc .Values.dbdata.root_password }}
