apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "lemp.fullname" . }}-dbpvc
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
spec:
  accessModes:
    - {{ .Values.pvcMariadb.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvcMariadb.storange }}
