apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-mariadb
  labels:
    app: {{ template "fullname" . }}-mariadb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:  
  ports:
    - port: {{ .Values.mariadb.servicePort }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  clusterIp: {{ .Values.mariadb.serviceType }}
  selector:
    app: {{ template "fullname" . }}-mariadb
    
