apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "fullname" . }}-mariadb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "fullname" . }}-mariadb
spec:
  serviceName: {{ template "fullname" . }}-mariadb
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-mariadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: {{ .Values.mariadb.strategyType }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-mariadb
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ template "fullname" . }}-mariadb
        - secretRef:
            name: {{ template "fullname" . }}-mariadb
        name: {{ template "fullname" . }}-mariadb
        image: "{{ .Values.mariadb.image }}"
        imagePullPolicy:  {{ .Values.mariadb.imagePullPolicy | quote }}
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: data
        - mountPath: /bitnami/mariadb/conf
          name: custom-cnf
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      volumes:
      - name: custom-cnf
        configMap:
          name: {{ template "fullname" . }}-mariadb
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
{{- if .Values.mariadb.persistence.storageClass }}
        volume.beta.kubernetes.io/storage-class: {{ .Values.mariadb.persistence.storageClass | quote }}
{{- else }}
        volume.alpha.kubernetes.io/storage-class: default
{{- end }}
    spec:
      accessModes:
      - {{ .Values.mariadb.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.mariadb.persistence.size | quote }}


