apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-mariadb
  labels:
    app: {{ template "fullname" . }}-mariadb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.mariadb.serviceType }}
  ports:
    - port: {{ .Values.mariadb.servicePort }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: {{ template "fullname" . }}-mariadb
    
