apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-{{ .Values.nginxService.name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  myapp.conf: |-
    server {
     listen 0.0.0.0:8080;
     server_name myapp.com;
     root /MOUNT_PATH/php-sample-app;
     location / {
        try_files $uri $uri/index.php;
     }

  location ~ \.php$ {
    # As php and nginx are in the same pod, we can access php-fpm service through localhost
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    include fastcgi.conf;
  }
}
