apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lemp.fullname" . }}-mariadb
  labels:
    app: {{ template "lemp.name" . }}-mariadb
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.secretMariadb.data.username }}
  password: {{ .Values.secretMariadb.data.password }}
