apiVersion: v1
data:
  dbname: azhzX3dvcmRwcmVzcw==
  dbpassword: KnRqYjN5QzFUQDh0
  dbprefix: azhf
  dbrootpassword: WHNkYXNkZmdxMk8=
  dbuser: azhzX3dvcmRwcmVzcw==
kind: Secret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: exercise-02
