apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-03
  labels:
    app: wordpress
    tier: frontend
    track: stable
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
      track: stable
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        track: stable
    spec:
      containers:
      - image: bitnami/wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: username-wordpress
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password-wordpress
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database-wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: host
        - name: WORDPRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: user-wordpress
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password-wordpress
        - name: WORDPRESS_BLOG_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: blog-name-wordpress
        - name: WORDPRESS_FIRST_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: first-name-wordpress
        - name: WORDPRESS_LAST_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: last-name-wordpress
        ports:
        - containerPort: 80
          name: wordpress
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
