apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: exercise-02
  labels:
    app: wordpress
    tier: frontend
    track: canary
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
      track: canary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        track: canary
    spec:
      containers:
      - image: bitnami/wordpress:4.9.5
        name: wordpress
        env:
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: username-wordpress
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password-wordpress
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database-wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
