apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: wordpress
   namespace: exercise-02
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image:  bitnami/wordpress:4.9.4
        name: wordpress
        env: 
          - name: ALLOW_EMPTY_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: allow_empty_password
          - name: MARIADB_HOST
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: mariadb_host
          - name: MARIADB_PORT_NUMBER
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: mariadb_port_number
          - name: WORDPRESS_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbuser
          - name: WORDPRESS_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress
                key: dbpassword
          - name: WORDPRESS_DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: wordpress
                key: wordpress_database_name
        ports:
          - name: http-server
            containerPort: 80
        readinessProbe:
          httpGet:
            path: /wp-login.php
            port: http-server
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /wp-login.php
            port: http-server
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
          - mountPath: /bitnami
            name: volumesdb
      restartPolicy: Always
      volumes:
        - name: volumesdb
          hostPath:
            path: /tmp/data/
            type: Directory
