apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: exercise-02
  labels:
    app: mariadb
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        tier: backend
    spec:
      containers:
      - image: bitnami/mariadb:latest
        name: mariadb
        envFrom:
          - configMapRef:
              name: mariadb-config
          - secretRef:
              name: mariadb-secrets
        livenessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "mysql -u${MARIADB_ROOT_USER} -p${MARIADB_ROOT_PASSWORD} -e \"select 1 from dual;\""
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: mariadb
          initialDelaySeconds: 20
          periodSeconds: 10
        ports:
          - name: mariadb
            containerPort: 3306
