apiVersion: "v1"
kind: "Service"
metadata:
  name: mariadb-svc
  namespace: exercise-02
spec:
  type: ClusterIP
  ports:
    - name: mariadb-port
      port: 3306
      targetPort: mariadb

  selector:
    app: mariadb
