{
 "title": "MariaDB (wordpress)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memoria MB",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_memory_used{app=\"wp-mariadb\"}/1024/1024"
    }
   ]
  },
  { "title": "Alertas", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 5, "y": 1 } },
  {
   "title": "Conexiones/5m",
   "type": "graph",
   "description": "Conexiones wordpress->mariadb",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_connections{app=\"wp-mariadb\"}[5m])",
     "legendFormat": "wp-mariadb"
    }
   ]
  },
  {
   "title": "Tablas Abiertas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_open_tables{app=\"wp-mariadb\"}",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}