kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exercise01:devs-team-api-rb
  namespace: team-api
subjects:
- kind: Group
  name: dev # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exercise01:devs-team-vision-rb
  namespace: team-vision
subjects:
- kind: Group
  name: dev # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
