{{ if eq .Values.hpa.enabled true }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscale
  namespace: default
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "lemp.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCpu }}
{{ end }}
