apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: exercise-03
  labels:
    app: wordpress
    service: frontend
spec:
  template:
    metadata:
      labels:
        app: wordpress
        service: frontend
    spec:
      containers:
      - image: bitnami/wordpress:latest
        name: wordpress
        env:
        - name: NAMI_DEBUG
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wordpress.log.level
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wordpress.mariadb.host
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: database.name
        - name: WORDPRESS_USERNAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wordpress.user.name
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-password
              key: password
        - name: WORDPRESS_BLOG_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wordpress.blog.name
        - name: WORDPRESS_FIRST_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wordpress.user.first
        - name: WORDPRESS_LAST_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: wordpress.user.last
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-mariadb-config
              key: database.user
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-password
              key: password
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 25
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 25
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10