apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
type: Opaque
data:
  dbName: {{ .Values.secretsmariadb.dbname | b64enc }}
  dbUser: {{ .Values.secretsmariadb.dbuser | b64enc }}
  dbPass: {{ .Values.secretsmariadb.dbpass | b64enc }}
