apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
data:
  myapp.conf: |-
    server {
      listen 0.0.0.0:8080;
      server_name myapp.com;

      root /MOUNT_PATH/php-sample-app;

      location / {
        try_files $uri $uri/index.php;
      }

      location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
         include fastcgi.conf;
      }
    }
