apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lemp.fullname" . }}-mariadb
  labels:
    app: {{ template "lemp.name" . }}-mariadb
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  database: {{ .Values.configmapMariadb.database }}
