{{- if .Values.autoscale.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "lemp.fullname" . }}
  namespace: {{.Values.namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: {{ template "lemp.fullname" . }}
  minReplicas: {{ .Values.autoscale.minReplicas }}
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscale.CPUpercentaje }} 

{{- end }}
