apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "lemp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "lemp.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: {{ .Values.intcont.deploy.name }}
        image: {{ .Values.intcont.deploy.image }}
        command: {{ .Values.intcont.deploy.command }}
        volumeMounts:
        - mountPath: /app
          name: code
      containers:
      - name: {{ .Values.containers.web.name }}
        image: {{ .Values.containers.web.image }}
        imagePullPolicy: {{ .Values.containers.web.pullPolicy }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - mountPath: /app
          name: code
        - mountPath: /bitnami/nginx/conf/vhosts
          name: vhost
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - name: {{ .Values.containers.php.name }}
        image: {{ .Values.containers.php.image }}
        imagePullPolicy: {{ .Values.containers.php.pullPolicy }}
        ports:
          - name: http-php
            containerPort: 9000
            protocol: TCP
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: {{ template "lemp.fullname" . }}
        - name: vhost
          configMap:
            name: {{ template "lemp.fullname" . }}
