kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "lemp.fullname" . }}
  labels:
    app: {{ template "lemp.name" . }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.pvc.web.accessmode }}
  resources:
    requests:
      storage: {{ .Values.pvc.web.storage }}
