apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "lemp.fullname" . }}-backend-depl
  namespace: exercise-03
  labels:
    app: {{ .Values.backend.name }}
    chart: {{ template "lemp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  volumeClaimTemplates:
  - metadata:
      name: backend-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "lemp.fullname" . }}-mariadb
          image: {{ .Values.backend.mariadb.image.repository }}:{{ .Values.backend.mariadb.image.tag }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ template "lemp.fullname" . }}-secret
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MARIADB_DATABASE
          ports:
            - name: dbport
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - "mysqladmin"
              - "ping"
              - "-u$MARIADB_USER"
              - "-p$MARIADB_PASSWORD"
          readinessProbe:
            exec:
              command:
              - "mysqladmin"
              - "ping"
              - "-u$MARIADB_USER"
              - "-p$MARIADB_PASSWORD"
          volumeMounts:
            - name: backend-data
              mountPath: {{ .Values.backend.persistence.mount_point }}
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
